Repository osmannkartall/knowzone, pull requests merged in 2023-04, with the labels that each got.

#187 Numeric key fix
  server/src/auth/authController.js
  server/src/auth/authService.js
  server/src/auth/user.js
  server/src/common/baseRepository.js
  server/src/form/form.js
  server/src/form/formController.js
  server/src/form/formRepository.js
  server/src/form/owner.js
  server/src/form/type.js
  server/src/post/post.js
  server/src/post/postController.js
  server/src/post/postRepository.js
  server/src/post/postSchemaConfigs.js
  server/src/search/searchController.js
  server/src/search/searchService.js
  server/test/form/formRepository.test.js
  server/test/post/postRepository.test.js
  server/test/search/searchService.test.js
  web/src/App.jsx
  web/src/components/common/ContentWrapper.jsx
  web/src/components/common/Creator.jsx
  web/src/components/common/FileUploader.jsx
  web/src/components/dashboard/Sidebar.jsx
  web/src/components/dashboard/Topbar.jsx
  web/src/components/form/FormCreator.jsx
  web/src/components/form/contentPreviews/EditorContentPreview.jsx
  web/src/components/form/contentPreviews/ImageContentPreview.jsx
  web/src/components/form/contentPreviews/ListContentPreview.jsx
  web/src/components/form/contentPreviews/TextContentPreview.jsx
  web/src/components/form/contentPreviews/getContentPreview.js
  web/src/components/post/PostCreator.jsx
  web/src/components/post/Posts.jsx
  web/src/components/post/contentParts/EditorContent.jsx
  web/src/components/post/contentParts/ImageContent.jsx
  web/src/components/post/contentParts/ListContent.jsx
  web/src/components/post/contentParts/TextContent.jsx
  web/src/components/post/contentParts/getContentPart.js
  web/src/components/post/defaultParts/Topics.jsx
  web/src/components/post/defaultParts/Type.jsx
  web/src/components/post/postCreatorSchema.js
  web/src/components/post/postCreatorUtils.js
  web/src/components/post/postSchemaConfigs.js
  web/src/components/post/postValidationMessages.js
  web/src/constants/routes.js
  web/src/pages/Home.jsx
  web/src/pages/PostsByOwner.jsx
  web/src/pages/PostsByType.jsx
  web/src/pages/SearchResults.jsx
  web/src/test/components/form/FormCreator.test.js
  web/src/test/components/post/PostCreator.test.js
  web/src/test/utils.js
Labels: bug, react

#193 update es version for eslint
  server/.eslintrc.json
Labels: refactor

#192 add graceful shutdown handlers
  server/src/app.js
  server/src/config/startDB.js
Labels: node, mongo

#195 fix error of navigating back to empty form
  web/src/components/post/Post.jsx
  web/src/components/post/Posts.jsx
  web/src/pages/PostsByType.jsx
Labels: bug, react

#197 add workflow files
  .github/workflows/test-knowzone-server.yml
  .github/workflows/test-knowzone-ui.yml
Labels: infra

#201 Form delete
  README.md
  server/init-db.sh
  server/src/common/baseRepository.js
  server/src/config/startDB.js
  server/src/form/formController.js
  server/src/scripts/dataGenerator.js
  web/src/components/common/ConfirmDialog.jsx
  web/src/pages/PostsByOwner.jsx
Labels: react, node, mongo, infra

#203 Fix type field structure
  server/init-db.sh
  server/src/form/form.js
  server/src/form/formController.js
  server/src/form/type.js
  server/src/post/post.js
  server/src/post/postController.js
  server/src/scripts/dataGenerator.js
  server/src/search/searchController.js
  server/src/search/searchService.js
  server/test/form/formRepository.test.js
  server/test/post/postRepository.test.js
  server/test/search/searchService.test.js
  web/src/__mocks__/api.js
  web/src/__mocks__/data.js
  web/src/api/forms/getFormByTypeId.js
  web/src/components/dashboard/Sidebar.jsx
  web/src/components/form/FormCreator.jsx
  web/src/components/form/formCreatorSchema.js
  web/src/components/post/Post.jsx
  web/src/components/post/PostCreator.jsx
  web/src/components/post/Posts.jsx
  web/src/components/post/postCreatorSchema.js
  web/src/components/search/SearchBar.jsx
  web/src/components/search/SearchOptions.jsx
  web/src/pages/PostsByOwner.jsx
  web/src/pages/SearchResults.jsx
  web/src/test/components/form/FormCreator.test.js
  web/src/test/components/post/PostCreator.test.js
Labels: react, node

#202 Replicaset infra
  .gitignore
  README.md
  db/data/README.md
  docker-compose.yml
  init-db.sh
  server/src/config/startDB.js
  server/src/scripts/dataGenerator.js
Labels: infra

#205 Share post
  server/src/form/formController.js
  server/src/post/postController.js
  web/src/App.jsx
  web/src/api/posts/getPostById.js
  web/src/components/dashboard/Sidebar.jsx
  web/src/components/dashboard/Topbar.jsx
  web/src/components/post/Post.jsx
  web/src/pages/PostsByOwner.jsx
  web/src/pages/SinglePost.jsx
Labels: react, node

#206 Explore component
  server/src/common/baseRepository.js
  server/src/config/connectRoutes.js
  server/src/post/postController.js
  server/src/scripts/dataGenerator.js
  server/src/search/searchController.js
  server/src/search/searchService.js
  web/src/App.jsx
  web/src/api/search/getPopularTopics.js
  web/src/components/common/Chips.jsx
  web/src/components/common/ContentWrapper.jsx
  web/src/components/common/MainContentWrapper.jsx
  web/src/components/common/MarkdownEditor.jsx
  web/src/components/common/ReadOnlyChips.jsx
  web/src/components/common/TopicChips.jsx
  web/src/components/dashboard/Content.jsx
  web/src/components/dashboard/Dashboard.jsx
  web/src/components/dashboard/MainContent.jsx
  web/src/components/dashboard/SideContent.jsx
  web/src/components/dashboard/Sidebar.jsx
  web/src/components/dashboard/Topbar.jsx
  web/src/components/explore/ExplorePosts.jsx
  web/src/components/explore/ExploreSideContent.jsx
  web/src/components/explore/PopularTopics.jsx
  web/src/components/form/FormCreator.jsx
  web/src/components/post/Post.jsx
  web/src/components/post/Posts.jsx
  web/src/components/search/SearchBar.jsx
  web/src/components/search/SearchOptions.jsx
  web/src/constants/colors.js
  web/src/constants/routes.js
  web/src/constants/styles.js
  web/src/pages/Explore.jsx
  web/src/pages/SinglePost.jsx
Labels: feature, react, node
