Repository osmannkartall/knowzone, pull requests merged in 2023-03, with the labels that each got.

#166 fix hot-reload problem
  web/package-lock.json
  web/package.json
Labels: react

#167 Search service
  server/package-lock.json
  server/package.json
  server/src/controllers/SearchController.js
  server/src/dataGenerator.js
  server/src/models/Post.js
  server/src/services/SearchService.js
  server/test/services/SearchService.test.js
Labels: node, mongo

#168 enable search for any form type
  server/src/dataGenerator.js
  server/src/models/schemaConfigs.js
  server/src/services/SearchService.js
  web/src/components/common/SearchBar.jsx
  web/src/components/common/SearchOptions.jsx
  web/src/constants/routes.js
  web/src/pages/SearchResults.jsx
  web/src/schemas/schemaConfigs.js
Labels: react, node

#171 Version upgrade
  server/.nvmrc
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/dataGenerator.js
  server/test/setupFile.js
  web/.nvmrc
  web/package-lock.json
  web/package.json
  web/src/App.jsx
  web/src/__mocks__/data.js
  web/src/api/getForms.js
  web/src/api/getPosts.js
  web/src/api/getPostsByType.js
  web/src/components/common/AppLogo.jsx
  web/src/components/common/AuthFormWrapper.jsx
  web/src/components/common/ContentWrapper.jsx
  web/src/components/common/CustomRoute.jsx
  web/src/components/common/FileUploader.jsx
  web/src/components/common/LinearProgressModal.jsx
  web/src/components/common/MarkdownEditor.jsx
  web/src/components/common/MarkdownPreview.jsx
  web/src/components/common/SearchBar.jsx
  web/src/components/common/SearchOptions.jsx
  web/src/components/common/TagPicker/TagPicker.jsx
  web/src/components/dashboard/Content.jsx
  web/src/components/dashboard/Dashboard.jsx
  web/src/components/dashboard/Sidebar.jsx
  web/src/components/dashboard/Topbar.jsx
  web/src/components/form/FormCreator.jsx
  web/src/components/post/Post.jsx
  web/src/components/post/PostCreator.jsx
  web/src/components/post/Posts.jsx
  web/src/constants/post-types.js
  web/src/contexts/AuthActions.jsx
  web/src/contexts/AuthContext.jsx
  web/src/index.jsx
  web/src/pages/Login.jsx
  web/src/pages/NotFound.jsx
  web/src/pages/PostsByOwner.jsx
  web/src/pages/PostsByType.jsx
  web/src/pages/Register.jsx
  web/src/pages/SearchResults.jsx
  web/src/test/components/form/FormCreator.test.js
  web/src/test/components/post/PostCreator.test.js
  web/src/utils.js
Labels: react, node

#172 add tests
  server/test/repositories/PostRepository.test.js
Labels: node

#176 make FormCreator responsive
  web/src/components/form/FormCreator.jsx
Labels: react

#178 add tests
  server/test/repositories/PostRepository.test.js
Labels: node

#180 Api schema validation
  server/src/controllers/FormController.js
  server/src/controllers/PostController.js
  server/src/middlewares/uploader.js
  server/src/models/Form.js
  server/src/models/Post.js
  server/src/models/formValidators.js
  server/src/models/postValidators.js
  server/src/validators.js
  server/test/middlewares/uploader.test.js
  web/src/components/form/FormCreator.jsx
  web/src/schemas/formCreatorSchema.js
  web/src/schemas/postCreatorSchema.js
  web/src/schemas/validationMessages.js
  web/src/schemas/validators.js
  web/src/test/components/post/PostCreator.test.js
Labels: react, node
